/*
 * File: gridHorarios.ui.js
 * Date: Wed May 30 2012 22:52:41 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridHorariosUi = Ext.extend(Ext.grid.GridPanel, {
    height: 200,
    initComponent: function() {
        this.columns = [
            {
                xtype: 'gridcolumn',
                dataIndex: 'string',
                header: 'Hora Inicio',
                sortable: true,
                width: 100
            },
            {
                xtype: 'numbercolumn',
                dataIndex: 'number',
                header: 'Hora Fin',
                sortable: true,
                width: 100,
                align: 'right'
            }
        ];
        gridHorariosUi.superclass.initComponent.call(this);
    }
});
