/*
 * File: tbpAdministracion.ui.js
 * Date: Wed May 30 2012 22:52:41 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

tbpAdministracionUi = Ext.extend(Ext.TabPanel, {
    activeTab: 0,
    width: 350,
    height: 350,
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                title: 'Horarios',
                style: 'padding:8px;',
                items: [
                    {
                        xtype: 'combo',
                        fieldLabel: 'Dispositivo'
                    },
                    {
                        xtype: 'fieldset',
                        title: 'Horarios',
                        bodyStyle: '',
                        style: 'border-width:1px 0 0 0;',
                        items: [
                            {
                                ref: '../../gridHorarios',
                                xtype: 'gridHorarios'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                title: 'Usuarios'
            },
            {
                xtype: 'panel',
                title: 'Dispositivos',
                disabled: true
            }
        ];
        tbpAdministracionUi.superclass.initComponent.call(this);
    }
});
