/*
 * File: tbpAdministracion.js
 * Date: Wed May 30 2012 22:32:13 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

tbpAdministracion = Ext.extend(tbpAdministracionUi, {
    initComponent: function() {
        tbpAdministracion.superclass.initComponent.call(this);
    }
});
