/*
 * File: gridMonitoreoHorarios.ui.js
 * Date: Sat May 19 2012 23:15:38 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridMonitoreoHorariosUi = Ext.extend(Ext.grid.GridPanel, {
    width: 330,
    height: 290,
    autoExpandColumn: 'colAccion',
    frame: true,
    initComponent: function() {
        this.columns = [
            {
                xtype: 'gridcolumn',
                header: 'Hora Inicio',
                dataIndex: 'horaInicio',
                sortable: true,
                width: 100
            },
            {
                xtype: 'gridcolumn',
                header: 'Hora Inicio',
                dataIndex: 'horaFin',
                sortable: true,
                width: 100
            },
            {
                xtype: 'gridcolumn',
                header: 'Evento',
                dataIndex: 'evento',
                sortable: true,
                id: 'colAccion'
            }
        ];
        this.bbar = {
            xtype: 'paging',
            displayInfo: true,
            displayMsg: '{0} - {1} de {2}',
            emptyMsg: 'No data',
            pageSize: 7
        };
        gridMonitoreoHorariosUi.superclass.initComponent.call(this);
    }
});
