/*
 * File: stoMonitoreoHorarios.js
 * Date: Sat May 19 2012 23:15:38 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

stoMonitoreoHorarios = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        stoMonitoreoHorarios.superclass.constructor.call(this, Ext.apply({
            storeId: 'MyStore',
            root: 'data',
            url: 'monitoreo/getHorarios',
            fields: [
                {
                    name: 'idHorario'
                },
                {
                    name: 'horaInicio'
                },
                {
                    name: 'horaFin'
                },
                {
                    name: 'evento'
                }
            ]
        }, cfg));
    }
});
new stoMonitoreoHorarios();