/*
 * File: frmAdminHorarios.ui.js
 * Date: Fri Jun 01 2012 16:04:02 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

frmAdminHorariosUi = Ext.extend(Ext.Panel, {
    title: 'My Panel',
    height: 385,
    unstyled: true,
    style: '',
    bodyStyle: 'padding:8px;',
    boxMaxWidth: 650,
    initComponent: function() {
        this.items = [
            {
                xtype: 'grid',
                width: 297,
                height: 290,
                autoExpandColumn: 'colNombre',
                frame: true,
                style: 'float:left;',
                columns: [
                    {
                        xtype: 'gridcolumn',
                        header: 'Nombre',
                        dataIndex: 'nombre',
                        sortable: true,
                        width: 150,
                        id: 'colNombre'
                    },
                    {
                        xtype: 'gridcolumn',
                        header: 'Tipo',
                        dataIndex: 'tipo',
                        sortable: true,
                        width: 100,
                        hidden: true,
                        id: 'colTipo'
                    },
                    {
                        xtype: 'gridcolumn',
                        header: 'Estado',
                        dataIndex: 'estado',
                        sortable: true,
                        width: 80
                    }
                ],
                bbar: {
                    xtype: 'paging',
                    displayInfo: true,
                    displayMsg: '{0} - {1} de {2}',
                    pageSize: 9,
                    emptyMsg: 'No data'
                }
            },
            {
                xtype: 'grid',
                width: 282,
                height: 290,
                autoExpandColumn: 'colEstado',
                frame: true,
                style: 'float:left;margin-left:20px;',
                columns: [
                    {
                        xtype: 'gridcolumn',
                        header: 'Hora Inicio',
                        dataIndex: 'horaInicio',
                        sortable: true,
                        width: 75
                    },
                    {
                        xtype: 'gridcolumn',
                        header: 'Hora Fin',
                        dataIndex: 'horaFin',
                        sortable: true,
                        width: 66
                    },
                    {
                        xtype: 'gridcolumn',
                        header: 'Estado',
                        sortable: true,
                        width: 80,
                        dataIndex: 'estado',
                        id: 'colEstado'
                    }
                ],
                bbar: {
                    xtype: 'paging',
                    displayInfo: true,
                    displayMsg: '{0} - {1} de {2}',
                    emptyMsg: 'No data',
                    pageSize: 7,
                    afterPageText: ' '
                },
                tbar: {
                    xtype: 'toolbar',
                    items: [
                        {
                            xtype: 'combo'
                        }
                    ]
                }
            },
            {
                xtype: 'form',
                style: 'float:left;margin-left:10px;',
                width: 250,
                height: 290,
                items: [
                    {
                        xtype: 'timefield',
                        fieldLabel: 'Label',
                        anchor: '100%'
                    },
                    {
                        xtype: 'timefield'
                    }
                ],
                bbar: {
                    xtype: 'toolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Guardar'
                        }
                    ]
                }
            }
        ];
        frmAdminHorariosUi.superclass.initComponent.call(this);
    }
});
