/*
 * File: frmAdminHorarios.ui.js
 * Date: Wed May 30 2012 23:27:05 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

frmAdminHorariosUi = Ext.extend(Ext.form.FormPanel, {
    width: 350,
    unstyled: true,
    style: '',
    bodyStyle: 'padding:8px;',
    boxMaxWidth: 350,
    initComponent: function() {
        this.items = [
            {
                xtype: 'combo',
                fieldLabel: 'Dispositivo'
            },
            {
                xtype: 'fieldset',
                title: 'Horarios',
                bodyStyle: '',
                style: 'border-width:1px 0 0 0;margin-top:30px;',
                items: [
                    {
                        width: 265,
                        ref: '../gridHorarios',
                        xtype: 'gridHorarios'
                    }
                ]
            }
        ];
        frmAdminHorariosUi.superclass.initComponent.call(this);
    }
});
