/*
 * File: frmAdminHorarios.js
 * Date: Wed May 30 2012 23:02:03 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

frmAdminHorarios = Ext.extend(frmAdminHorariosUi, {
    initComponent: function() {
        frmAdminHorarios.superclass.initComponent.call(this);
    }
});
Ext.reg('frmAdminHorarios', frmAdminHorarios);