/*
 * File: frmAdminHorarios.ui.js
 * Date: Sat Jun 02 2012 07:03:55 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

frmAdminHorariosUi = Ext.extend(Ext.Panel, {
    width: 580,
    unstyled: true,
    style: '',
    bodyStyle: 'padding:8px;',
    boxMaxWidth: 650,
    layout: 'form',
    initComponent: function() {
        this.items = [
            {
                xtype: 'displayfield',
                value: '<div class="titulo">Programación Semanal</div>',
                anchor: '100%',
                hideLabel: true,
                style: 'text-align:center;',
                ref: 'dspTitulo'
            },
            {
                xtype: 'fieldset',
                title: 'Seleccione ',
                layout: 'hbox',
                style: 'border-width:1px 0 0 0;',
                items: [
                    {
                        xtype: 'container',
                        layout: 'form',
                        labelAlign: 'top',
                        width: 350,
                        items: [
                            {
                                xtype: 'combo',
                                width: 250,
                                fieldLabel: 'Dispositivo',
                                store: 'stoDispositivos',
                                ref: '../../cmbDispositivos'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        layout: 'form',
                        labelAlign: 'top',
                        flex: 1,
                        items: [
                            {
                                xtype: 'combo',
                                fieldLabel: 'Dia de la semana',
                                width: 150,
                                store: 'stoDias',
                                ref: '../../cmbDias'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Configuracion de Horarios',
                height: 266,
                style: 'border-width:1px 0 0 0;',
                items: [
                    {
                        xtype: 'grid',
                        title: 'Horarios del dia',
                        width: 282,
                        height: 216,
                        autoExpandColumn: 'colEstado',
                        frame: true,
                        style: 'float:left;',
                        boxMaxWidth: 282,
                        ref: '../gridHorarios',
                        columns: [
                            {
                                xtype: 'gridcolumn',
                                header: 'Hora Inicio',
                                dataIndex: 'horaInicio',
                                sortable: true,
                                width: 75
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Hora Fin',
                                dataIndex: 'horaFin',
                                sortable: true,
                                width: 66
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Estado',
                                sortable: true,
                                width: 80,
                                dataIndex: 'estado',
                                id: 'colEstado'
                            }
                        ],
                        bbar: {
                            xtype: 'paging',
                            displayInfo: true,
                            displayMsg: '{0} - {1} de {2}',
                            emptyMsg: 'No data',
                            pageSize: 7,
                            afterPageText: ' '
                        }
                    },
                    {
                        xtype: 'form',
                        title: 'Edicion de Horario',
                        style: 'float:left;margin-left:10px;',
                        width: 240,
                        height: 215,
                        frame: true,
                        ref: '../frmEdicion',
                        bbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Nuevo',
                                    icon: 'http://saw/imagenes/add1.png'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Borrar',
                                    disabled: true,
                                    icon: 'http://saw/imagenes/list_remove.png'
                                }
                            ]
                        },
                        items: [
                            {
                                xtype: 'fieldset',
                                items: [
                                    {
                                        xtype: 'timefield',
                                        emptyText: '10:30 AM',
                                        fieldLabel: 'Fecha Inicio',
                                        width: 100
                                    },
                                    {
                                        xtype: 'combo',
                                        fieldLabel: 'Fecha Fin',
                                        width: 100,
                                        emptyText: '12:00 PM'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                title: 'Estado',
                                hideLabels: true,
                                layout: 'hbox',
                                height: 60,
                                items: [
                                    {
                                        xtype: 'radio',
                                        fieldLabel: 'Label',
                                        boxLabel: 'Activo',
                                        anchor: '100%',
                                        style: 'margin-left:20px;',
                                        flex: 1
                                    },
                                    {
                                        xtype: 'radio',
                                        fieldLabel: 'Label',
                                        boxLabel: 'Cancelado',
                                        anchor: '100%',
                                        style: 'margin-left:40px;',
                                        flex: 1
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ];
        frmAdminHorariosUi.superclass.initComponent.call(this);
    }
});
