/*
 * File: gridHorarios.js
 * Date: Wed May 30 2012 23:07:01 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

gridHorarios = Ext.extend(gridHorariosUi, {
    initComponent: function() {
        gridHorarios.superclass.initComponent.call(this);
    }
});
Ext.reg('gridHorarios', gridHorarios);